server:
  port: 8081
spring:
  application:
    name: service-provider
  datasource:
    druid:
      url: jdbc:mysql://10.1.74.191:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: xiann
      validation-query: SELECT 'x'
      max-wait: 60000
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:8080/eureka/      #服务注册中信地址，含有BASIC认证的用户名和密码
  instance:
    prefer-ip-address: true         #将IP注册到服务注册中心

#放开所有节点
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root : warn
    com :
      cloud :
        provider : debug


